### ISSUE TITLE
Project's roadmap

### ISSUE THREAD

**Issue by lsrdg** [skilldex/jugglerecommender#7]
Hey guys, what a great project you've came up with! I would love to contribute. 

Basically the title: is there a roadmap or at least some `beginner-friendly` issues?

I'm quite new to javascript though and I'm still just reading through the code to understand it. There are some features that I would love to see on the project, but I would rather wait with them and maybe take care of low hanging fruits for now.

For instance, if documentation is a concern, I would be glad to help with that.

Thanks again!

**Comment by ianboru** [comment]
Hey thanks for your interest! If you check the todo.txt there is a variety of tasks that are categorized. Take a look if there are any tasks that you think you can handle and let us know if you have any questions! One of us can probably take some time to orient you if you need a high level overview but in general it's best if you can ask specific questions.

**Comment by ianboru** [comment]
In addition, the web app is written in react so as you look for how to do stuff, if you can't find something relevant by searching "how to do X in javascript", try "how to do X in react"

**Comment by lsrdg** [comment]
Thanks for bringing attention to `todo.txt`, that's what I was looking for. (:
It might take a while for me to feel comfortable enough to commit code (without wasting your time), but I would be glad to get started working on documenting the project (if that's a concern of course).

Thanks for taking the time and for the project!
